baseurl         = "https://rudethoughts.com/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "rudethoughts-1"
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Rude Thoughts"
  subtitle    = "Let's think a little"
  copyright   = "© 2018"
  cover       = "uploads/header_image.jpg"
  description = "Rude Thoughts...Let's think a little"
  metaDescription = ""
  googleAnalytics = "UA-88370265-3"
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = "JRudeThoughts"
  githubName = ""

  logo = ""
  orgName = "Rude Thoughts"
  orgWebsite = "https://www.rudethoughts.com"
  orgDescription = ""

  author = "Jerry Rude"
  authorAvatar = "uploads/author_JerryRude.jpg"
  authorLocation = "Dayton, OH"
  authorWebsite = "https://rudethoughts.com/author/jerryrude"
  authorDescription = "Hunter, Outdoorsman, Aspiring Economist"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Thoughts"
  url = "/thought/"
  weight = 100

[[menu.main]]
  name = "Daily Ponder"
  url = "/ponder/"
  weight = 99

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 98

