baseurl         = "https://rudethoughts.com/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Rude Thoughts"
  subtitle    = "Let's talk a little"
  copyright   = "© 2018"
  cover       = "uploads/header_image.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "eueung"

  logo = ""
  orgName = "Rude Thoughts"
  orgWebsite = "https://www.rudethoughts.com"
  orgDescription = "Listen "

  author = "Jerry Rude"
  authorAvatar = "uploads/author_JerryRude.jpg"
  authorLocation = "Dayton, OH"
  authorWebsite = "https://rudethoughts.com"
  authorDescription = "Hunter, Gatherer, Environmentalist"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Thoughts"
  url = "/categories/thoughts/"
  weight = 100

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 99

