backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "date"}
          - {label: "No Author", name: "noauthor", widget: hidden, default: "true"}
          - {label: "Comments", name: "comments", widget: hidden, default: "false"}
          - {label: "Share", name: "share", widget: hidden, default: "false"}
          - {label: Body, name: body, widget: markdown}
  - name: "thought"
    label: "Thought"
    folder: "content/thought"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Draft, name: draft, widget: boolean, default: true}
      - {label: Date, name: date, widget: date, required: true}
      - {label: Author, name: author, widget: select, options: [Jerry Rude, Austin Eidemiller], required: true}
      - label: Author Image
        name: authorAvatar
        widget: select
        required: true
        options: 
          - {label: "Jerry Rude", value: "uploads/author_JerryRude.jpg"}
          - {label: "Austin Eidemiller", value: "uploads/author_AustinEidemiller.jpg"}
      - {label: "Image", name: image, widget: image, required: false}
      - {label: Categories, name: categories, widget: hidden, default: "thought"}
      - {label: Tags, name: tags, widget: list, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Sharing, name: share, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: post}
      - {label: Thought, name: body, widget: markdown}
  - name: "ponder"
    label: "Ponder"
    folder: "content/ponder"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Draft, name: draft, widget: boolean, default: true}
      - {label: Date, name: date, widget: date, required: true}
      - {label: Author, name: author, widget: select, options: [Jerry Rude, Austin Eidemiller], required: true}
      - label: Author Image
        name: authorAvatar
        widget: select
        required: true
        options: 
          - {label: "Jerry Rude", value: "uploads/author_JerryRude.jpg"}
          - {label: "Austin Eidemiller", value: "uploads/author_AustinEidemiller.jpg"}
      - {label: "Image", name: image, widget: image, required: false}
      - {label: Categories, name: categories, widget: hidden, default: "ponder"}
      - {label: Tags, name: tags, widget: list, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Sharing, name: share, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: post}
      - {label: Thought, name: body, widget: markdown}
