backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "date"}
          - {label: "No Author", name: "noauthor", widget: hidden, default: "true"}
          - {label: "Comments", name: "comments", widget: hidden, default: "false"}
          - {label: "Share", name: "share", widget: hidden, default: "false"}
          - {label: Body, name: body, widget: markdown}